# This is a syncronisation workflow to that pulls the latest documentation from the lammps repository
# and builds an updated vsix-package based on these files.

name: SYNC

on:
  schedule:
    - cron: '45 11 1 * *'

  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 
    - uses: actions/setup-node@v1
    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
          
    - name: Download updated Docs
      id: s1
      run:
        svn export https://github.com/lammps/lammps/branches/release/doc/src rst --force

    - name: Build Docs TS-Object
      id: s2
      if: steps.s1.conclusion == 'success'
      run: |
        python3 -m pip install --upgrade pip
        pip3 install numpy
        python3 ./rst2json/rst2JSON.py
    
    - name: Check for updated docs
      id: s3
      if: steps.s2.conclusion == 'success'
      run: |
        git config --global user.name 'thfriedrich'
        git config --global user.email 'thfriedrich@users.noreply.github.com'
        git config --global pull.ff only
        git add .
        # Check if Lammps Docs were updated
        if ! [[ $(git status) == *"nothing to commit, working tree clean"* ]]; then
          echo "b_update=true"  >> $GITHUB_ENV
        else
          # Check if vscode-Lammps master branch had commits since last tag
          n_com=$(git rev-list $(git describe --tags --abbrev=0 @^)..master --count)
          if [ "$n_com" -gt "0" ];then
            echo "b_update=true"  >> $GITHUB_ENV
          fi
        fi

    - name: Setup node
      id: s4
      if: steps.s3.conclusion == 'success' && env.b_update == 'true'
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Build package
      id: s5
      if: steps.s4.conclusion == 'success' && env.b_update == 'true'
      run: |
        sudo apt install imagemagick -y
        bash ./scripts/resize256.sh
        npm install
        npm install -g vsce
        npm audit fix
        git add .
        git commit -m "Scheduled sync of lammps_vscode with Lammps documentation $(date +'%Y-%m-%d')"
        npm version patch
        git push
        vsce package

              
    - name: Get Tag and Date
      id: s6
      if: steps.s5.conclusion == 'success' && env.b_update == 'true'
      run: | 
        echo "::set-output name=date::$(date +'%Y-%m-%d')"
        echo "::set-output name=vsix_file::$(find *.vsix)"
        echo "::set-output name=tag::$(find *.vsix | cut -d'.' -f1-3 | cut -d'-' -f2-3)"
        echo "::set-output name=lmp_version::$(curl --silent "https://api.github.com/repos/lammps/lammps/releases/latest" | grep -Po '"tag_name": "\K.*?(?=")')"
    
    - name: Create Release
      id: s7
      if: steps.s6.conclusion == 'success' && env.b_update == 'true'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.s6.outputs.tag }}-sync${{ steps.s6.outputs.date }}
        release_name: v${{ steps.s6.outputs.tag }} Sync Release - ${{ steps.s6.outputs.date }}
        body: Scheduled synchronisation of lammps_vscode with Lammps documentation from ${{ steps.s6.outputs.date }}. This version corresponds to lammps release ${{ steps.s6.outputs.lmp_version }}.
        draft: false
        prerelease: false   

    - name: Publish2GitHub
      id: s8
      if: steps.s7.conclusion == 'success' && env.b_update == 'true'
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        releaseId: ${{ steps.s7.outputs.id }} 
        args: ${{ steps.s6.outputs.vsix_file }}

    - name: Publish2Marketplace
      id: s9
      if: steps.s8.conclusion == 'success' && env.b_update == 'true'
      run: vsce publish
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
  
        
        
